"""Bespoke fetch/parse core for the OHLCV leg of ``bhistory``.

HistoricoData takes a single start tag (10077) and returns every session
from it through today (the 1789 end tag other endpoints honor is ignored
here), so the window end is cut client-side. Bespoke (not spec-driven) for
that filtering; the close leg of ``bhistory`` is spec-driven
(SPEC_BHISTORY over HistoricoDiarioSimbolos). The hand-written async
source; the sync twin is generated by ``scripts/gen_sync.py``.
"""

from __future__ import annotations

import xml.etree.ElementTree as ET

import httpx
import pandas as pd

from ..._core.constants import BASE_URL
from ..._core.exceptions import ContentProxyError
from ..._core.logging import get_logger
from ..._core.ratelimit import rate_limit_async
from ..._core.retry import http_retry
from ..columns import CONTENT_PROXY_RENAME, DAILY_OHLCV_SCHEMA
from ..http import base_params, get_async_http_client, get_session_token
from ..output import Index, finalize_frame
from ..xml_helpers import parse_ticks, raise_for_content_proxy_status

logger = get_logger(__name__)


@http_retry
async def _ohlcv_fetch(s: httpx.AsyncClient, params: dict) -> httpx.Response:
    """Isolated HTTP call for retry."""
    return await s.get(
        f"{BASE_URL}/BaseHistoricaNumerica/HistoricoData",
        params=params,
        timeout=30,
    )


async def ohlcv_core(
    ticker: str,
    start_str: str,
    end_str: str,
    session_token: str | None = None,
) -> pd.DataFrame:
    """One symbol's daily OHLCV over a window (dates already normalized)."""
    token = get_session_token(session_token)
    s = get_async_http_client()

    params = base_params(token)
    params["305"] = ticker
    params["10077"] = start_str

    logger.debug("bhistory ohlcv: %s %s-%s", ticker, start_str, end_str)
    await rate_limit_async()
    r = await _ohlcv_fetch(s, params)

    try:
        root = ET.fromstring(r.text)
    except ET.ParseError as exc:
        logger.error("bhistory ohlcv: XML parse error: %s", exc)
        raise ContentProxyError(
            f"bhistory ohlcv: malformed XML response: {exc}",
            endpoint="BaseHistoricaNumerica/HistoricoData",
        ) from exc
    raise_for_content_proxy_status(root, "BaseHistoricaNumerica/HistoricoData", params)

    rows = [r for r in parse_ticks(root, sort_by="dat") if r.get("dat", "") <= end_str]
    df = finalize_frame(
        rows,
        index=Index.DATETIME,
        rename=CONTENT_PROXY_RENAME,
        schema=DAILY_OHLCV_SCHEMA,
    )
    df.insert(0, "ticker", ticker)
    return df
