"""Bespoke fetch/parse core for the OHLCV leg of ``bhistory``.

HistoricoData is a single-day endpoint: ``10077=date`` returns that one
session's OHLCV tick and nothing else (no end tag widens it). A multi-day
window therefore needs one request per trading day. The trading days are read
once from the close leg (HistoricoDiarioSimbolos serves the whole window in a
single call), then each day's OHLCV is fetched and the rows concatenated.

Bespoke (not spec-driven) for that per-day fan-out; the close leg of
``bhistory`` is spec-driven (SPEC_BHISTORY). The hand-written async source;
the sync twin is generated by ``scripts/gen_sync.py``.
"""

from __future__ import annotations

import pandas as pd

from ..columns import CONTENT_PROXY_RENAME, DAILY_OHLCV_SCHEMA
from ..output import Index, finalize_frame
from ..xml_helpers import parse_ticks
from .transport import content_proxy_get


async def _trading_days(
    ticker: str, start_str: str, end_str: str, token: str | None
) -> list[str]:
    """The window's trading days for a symbol, from the close leg (one call)."""
    root = await content_proxy_get(
        "BaseHistoricaNumerica/HistoricoDiarioSimbolos",
        {"10113": ticker, "961": start_str, "1789": end_str},
        session_token=token,
    )
    return sorted({r["dat"] for r in parse_ticks(root) if r.get("dat")})


async def _ohlcv_day(ticker: str, day: str, token: str | None) -> dict | None:
    """One trading day's OHLCV tick (HistoricoData), or None if absent."""
    root = await content_proxy_get(
        "BaseHistoricaNumerica/HistoricoData",
        {"305": ticker, "10077": day},
        session_token=token,
    )
    ticks = parse_ticks(root)
    return ticks[0] if ticks else None


async def ohlcv_core(
    ticker: str,
    start_str: str,
    end_str: str,
    session_token: str | None = None,
) -> pd.DataFrame:
    """One symbol's daily OHLCV over a window (dates already normalized)."""
    days = await _trading_days(ticker, start_str, end_str, session_token)
    rows = []
    for day in days:
        tick = await _ohlcv_day(ticker, day, session_token)
        if tick:
            rows.append(tick)
    df = finalize_frame(
        rows,
        index=Index.DATETIME,
        rename=CONTENT_PROXY_RENAME,
        schema=DAILY_OHLCV_SCHEMA,
    )
    df.insert(0, "ticker", ticker)
    return df
