# GENERATED by scripts/gen_sync.py from _legacy/_async/bdh.py — DO NOT EDIT.
"""Bespoke fetch/parse cores for bdh and bdh_ohlcv.

These two endpoints are deliberately NOT spec-driven (chunked multi-date
fetch, hand-built XML rows — see ``_legacy/spec.py``); their cores live here
so the sync twins are generated instead of hand-mirrored.
"""

from __future__ import annotations

import xml.etree.ElementTree as ET

import httpx
import pandas as pd

from ..._core.constants import BASE_URL
from ..._core.dates import to_date_str
from ..._core.exceptions import ContentProxyError
from ..._core.logging import get_logger
from ..._core.ratelimit import rate_limit
from ..._core.retry import http_retry
from ..columns import CONTENT_PROXY_RENAME, DAILY_OHLCV_SCHEMA
from ..http import base_params, get_http_client, get_session_token
from ..output import Index, empty_bdh_frame, finalize_frame
from ..xml_helpers import raise_for_content_proxy_status

logger = get_logger(__name__)


@http_retry
def _bdh_fetch(s: httpx.Client, params: dict) -> httpx.Response:
    """Isolated HTTP call for retry."""
    return s.get(
        f"{BASE_URL}/BaseHistoricaNumerica/HistoricoFechamentos",
        params=params,
        timeout=30,
    )


@http_retry
def _bdh_ohlcv_fetch(s: httpx.Client, params: dict) -> httpx.Response:
    """Isolated HTTP call for retry."""
    return s.get(
        f"{BASE_URL}/BaseHistoricaNumerica/HistoricoData",
        params=params,
        timeout=15,
    )


def bdh_core(
    tickers: list[str],
    dates: list[str],
    session_token: str | None = None,
) -> pd.DataFrame:
    """Fetch+assemble historical closing prices over a business-day list.

    One request per chunk of 250 dates (URL length limit), all tickers in one
    tag. Rows are grouped by SYMBOL, tolerance rows with no trade data (NaT
    index) dropped, and the per-symbol blocks concatenated with a ``ticker``
    column.
    """
    token = get_session_token(session_token)
    s = get_http_client()
    results: dict[str, list[dict[str, str]]] = {}

    CHUNK = 250
    for i in range(0, len(dates), CHUNK):
        chunk_dates = dates[i : i + CHUNK]
        params = base_params(token)
        params["10113"] = ";".join(tickers)
        params["DatasTolerancia"] = ";".join(chunk_dates)

        logger.debug("bdh: fetching %d dates for %s", len(chunk_dates), tickers)
        rate_limit()
        r = _bdh_fetch(s, params)

        try:
            root = ET.fromstring(r.text)
        except ET.ParseError as exc:
            logger.error("bdh: XML parse error: %s", exc)
            raise ContentProxyError(
                f"bdh: malformed XML response: {exc}",
                endpoint="BaseHistoricaNumerica/HistoricoFechamentos",
            ) from exc
        raise_for_content_proxy_status(
            root, "BaseHistoricaNumerica/HistoricoFechamentos", params
        )

        for tick in root.findall(".//TICK"):
            sym = tick.findtext("SYMBOL") or ""
            row = {
                "dat": tick.findtext("DAT") or "",
                "last": tick.findtext("LAST") or "",
                "settle": tick.findtext("SETTLE") or "",
                "settle_rate": tick.findtext("SETTLE_RATE") or "",
                "yield": tick.findtext("YIELD") or "",
                "dattol": tick.findtext("DATTOL") or "",
            }
            results.setdefault(sym, []).append(row)

    for sym in results:
        results[sym].sort(key=lambda r: r["dat"])

    frames = []
    for sym in sorted(results):
        df = finalize_frame(
            results[sym], index=Index.DATETIME, rename=CONTENT_PROXY_RENAME
        )
        # Drop tolerance rows with no actual trade data (NaT index)
        df = df[df.index.notna()]
        if df.empty:
            continue
        df.insert(0, "ticker", sym)
        frames.append(df)

    if not frames:
        return empty_bdh_frame()
    return pd.concat(frames)


def bdh_ohlcv_one(
    ticker: str,
    date: str,
    session_token: str | None = None,
) -> pd.DataFrame:
    """Get full OHLCV data for a single ticker on a single date."""
    token = get_session_token(session_token)
    s = get_http_client()
    date_str = to_date_str(date)

    params = base_params(token)
    params["305"] = ticker
    params["10077"] = date_str
    params["Precisao"] = "2"

    logger.debug("bdh_ohlcv: %s on %s", ticker, date_str)
    rate_limit()
    r = _bdh_ohlcv_fetch(s, params)

    try:
        root = ET.fromstring(r.text)
    except ET.ParseError as exc:
        logger.error("bdh_ohlcv: XML parse error: %s", exc)
        raise ContentProxyError(
            f"bdh_ohlcv: malformed XML response: {exc}",
            endpoint="BaseHistoricaNumerica/HistoricoData",
        ) from exc
    raise_for_content_proxy_status(root, "BaseHistoricaNumerica/HistoricoData", params)

    tick = root.find(".//TICK")
    rows = (
        [{child.tag.lower(): (child.text or "") for child in tick}]
        if tick is not None
        else []
    )
    df = finalize_frame(
        rows,
        index=Index.DATETIME,
        rename=CONTENT_PROXY_RENAME,
        schema=DAILY_OHLCV_SCHEMA,
    )
    df.insert(0, "ticker", ticker)
    return df
