# GENERATED by scripts/gen_sync.py from _legacy/_async/markit.py — DO NOT EDIT.
"""Markit CDS I/O core: dates, entity listing, and term-structure curves.

Bespoke core (like ``bdh``): the MarkitOutput2 wire format is RECORD-based XML
rather than TICKs, and one public call fans out over up to three endpoints
(date resolution -> entity resolution -> curve), so it does not fit the
declarative ``EndpointSpec`` executor. Pure parsing/resolution lives in
``_legacy/markit.py``.
"""

from __future__ import annotations

import pandas as pd

from ..._core.exceptions import NotFoundError
from ..markit import (
    CDS_CURVE_SCHEMA,
    CDS_ENTITY_SCHEMA,
    CDS_INDEX_SCHEMA,
    curve_record_to_rows,
    entity_rows_to_records,
    index_records_to_rows,
    latest_cds_date,
    latest_markit_date,
    markit_records,
    match_cds_entities,
    pick_cds_entity,
)
from ..output import Index, finalize_frame
from .transport import content_proxy_get


def bcds_core(
    entity: str | None,
    date_iso: str | None,
    cds_type: str,
    tier: str | None,
    docclause: str | None,
    session_token: str | None = None,
) -> pd.DataFrame:
    """Shared core behind ``bcds``/``abcds``; inputs already normalized.

    With ``date_iso=None`` the most recent date carrying data for ``cds_type``
    is resolved via ListaDatas. With ``entity=None`` the entity listing for the
    date is returned; otherwise the entity's (tier, docclause) listing is
    resolved via ListaCDS and its term structure fetched as one row per tenor.
    """
    if date_iso is None:
        root = content_proxy_get(
            "MarkitOutput2/ListaDatas", {"13336": "C"}, session_token
        )
        date_iso = latest_cds_date(markit_records(root), cds_type)
        if date_iso is None:
            schema = CDS_ENTITY_SCHEMA if entity is None else CDS_CURVE_SCHEMA
            return finalize_frame([], index=Index.RANGE, schema=schema)

    root = content_proxy_get(
        "MarkitOutput2/ListaCDS", {"10047": date_iso}, session_token
    )
    entity_rows = markit_records(root)

    if entity is None:
        return finalize_frame(
            entity_rows_to_records(entity_rows, date_iso),
            index=Index.RANGE,
            schema=CDS_ENTITY_SCHEMA,
        )

    matches = match_cds_entities(entity_rows, entity, cds_type, tier, docclause)
    if not matches:
        if not entity_rows:
            # Explicit date with no Markit coverage: valid-but-empty, not a
            # bad entity (the entity cannot be checked against an empty list).
            return finalize_frame([], index=Index.RANGE, schema=CDS_CURVE_SCHEMA)
        raise NotFoundError(entity, kind="cds entity")
    chosen = pick_cds_entity(matches, entity)

    root = content_proxy_get(
        "MarkitOutput2/CDS",
        {
            "10047": date_iso,
            "13339": chosen["TIPOCDS"],
            "13349": chosen["IDCDS"],
            "13350": chosen["TIER"],
            "13351": chosen["DOCCLAUSE"],
        },
        session_token,
    )
    records = markit_records(root)
    rows = curve_record_to_rows(records[0], chosen, date_iso) if records else []
    return finalize_frame(rows, index=Index.RANGE, schema=CDS_CURVE_SCHEMA)


def bcds_indices_core(
    date_iso: str | None,
    session_token: str | None = None,
) -> pd.DataFrame:
    """Shared core behind ``bcds_indices``/``abcds_indices``.

    Returns the Markit CDS index term-structure table (CDXEM, iTraxx, etc.)
    for ``date_iso``; with ``date_iso=None`` the most recent date the feed
    carries is resolved via ListaDatas.
    """
    if date_iso is None:
        root = content_proxy_get(
            "MarkitOutput2/ListaDatas", {"13336": "C"}, session_token
        )
        date_iso = latest_markit_date(markit_records(root))
        if date_iso is None:
            return finalize_frame([], index=Index.RANGE, schema=CDS_INDEX_SCHEMA)

    root = content_proxy_get(
        "MarkitOutput2/Indices", {"10047": date_iso}, session_token
    )
    rows = index_records_to_rows(markit_records(root), date_iso)
    return finalize_frame(rows, index=Index.RANGE, schema=CDS_INDEX_SCHEMA)
