# GENERATED by scripts/gen_sync.py from _legacy/_async/resolve.py — DO NOT EDIT.
"""Ticker -> CVM and indicator name -> ID resolution.

The process-lifetime caches and the pure matching/extraction helpers live in
``_legacy/resolve_state.py``, shared with the generated sync twin.
"""

from __future__ import annotations

from ..resolve_state import (
    cvm_cache,
    cvm_from_quote,
    indicator_cache_loaded,
    load_indicator_cache,
    match_indicator,
)
from .quote import quote_one


def resolve_cvm(ticker: str, session_token: str | None = None) -> int:
    """Resolve a ticker symbol to its CVM company code.

    Uses the scalar quote primitive internally. Results are cached for the
    process lifetime (cache shared between the sync and async resolvers).

    Args:
        ticker: B3 ticker symbol (e.g., "PETR4", "VALE3").
        session_token: Optional explicit BCAA session token.

    Returns:
        CVM numeric code (e.g., 9512 for PETR4).

    Raises:
        NotFoundError: If the ticker cannot be resolved.
    """
    key = ticker.strip().upper()
    if key in cvm_cache:
        return cvm_cache[key]
    quote = quote_one(key, session_token=session_token)
    return cvm_from_quote(key, quote)


def resolve_indicator(name_or_id: str | int, session_token: str | None = None) -> int:
    """Resolve an indicator name or ID to its numeric ID.

    Accepts:
        - int or digit string -> returned directly
        - str -> fuzzy-matched against the indicator metadata names
          (exact > startswith > contains; case- and accent-insensitive)

    Args:
        name_or_id: Indicator ID (int) or name (str, e.g. "EBITDA", "ROE").
        session_token: Optional explicit BCAA session token.

    Returns:
        Numeric indicator ID.

    Raises:
        ValidationError: If the name is ambiguous or not found.
    """
    # Fast path: already numeric
    if isinstance(name_or_id, int):
        return name_or_id
    s = str(name_or_id).strip()
    if s.isdigit():
        return int(s)

    if not indicator_cache_loaded():
        # Lazy import: the executor imports this module (executor <-> resolve)
        from ..endpoints import SPEC_BINDICATOR_META
        from .executor import run_spec

        load_indicator_cache(
            run_spec(SPEC_BINDICATOR_META, session_token=session_token)
        )
    return match_indicator(s)
