# GENERATED by scripts/gen_sync.py from _legacy/_async/ticks.py — DO NOT EDIT.
"""Times-and-trades core: B3 tick data with top-of-book quotes.

Bespoke core (like ``bdh``): TimesTrades emits DD/MM/YYYY dates and a full
exchange timestamp per row, which the declarative executor's index policies
do not parse, and the output index is tz-aware (UTC wire -> Sao Paulo). The
hand-written async source; the sync twin is generated by
``scripts/gen_sync.py``.
"""

from __future__ import annotations

import pandas as pd

from ..._core.logging import get_logger
from ..xml_helpers import parse_ticks
from .transport import content_proxy_get

logger = get_logger(__name__)

# Output column order. TRD rows fill price/size/seq_num with the trade and
# the participant ids are the buyer (bid side) and seller (ask side) brokers;
# QTE rows fill the four book fields with the top of book and the participant
# ids identify the standing orders. The wire dat/hor pair duplicates
# exch_time (the index) and load_time/line_time are feed-transport
# timestamps — all four are dropped.
TICKS_COLUMNS = [
    "type",
    "price",
    "size",
    "bid_price",
    "bid_size",
    "ask_price",
    "ask_size",
    "bid_participant",
    "ask_participant",
    "seq_num",
]


def _empty_ticks() -> pd.DataFrame:
    df = pd.DataFrame(
        {
            col: pd.Series(dtype="object" if col == "type" else "float64")
            for col in TICKS_COLUMNS
        }
    )
    df.index = pd.DatetimeIndex([], tz="America/Sao_Paulo")
    return df


def bticks_core(
    ticker: str,
    start_str: str,
    end_str: str,
    session_token: str | None = None,
) -> pd.DataFrame:
    """One symbol's times-and-trades over a UTC window (already normalized).

    Returns a frame indexed by the exchange timestamp converted to
    America/Sao_Paulo, oldest row first. An empty window yields the typed
    empty frame.
    """
    logger.debug("bticks: %s %s-%s", ticker, start_str, end_str)
    root = content_proxy_get(
        "BaseHistoricaNumerica/TimesTrades",
        {"305": ticker, "10071": start_str, "10072": end_str},
        session_token=session_token,
        timeout=60,
    )
    rows = parse_ticks(root)
    if not rows:
        return _empty_ticks()
    rows.reverse()  # server emits newest first; restore chronological order

    raw = pd.DataFrame(rows)
    index = pd.DatetimeIndex(
        pd.to_datetime(raw["exch_time"], format="%d/%m/%Y %H:%M:%S.%f", utc=True)
    ).tz_convert("America/Sao_Paulo")
    source = {
        "type": raw["tick_type"],
        "price": raw["last"],
        "size": raw["size"],
        "bid_price": raw["bid_price"],
        "bid_size": raw["bid_size"],
        "ask_price": raw["ask_price"],
        "ask_size": raw["ask_size"],
        "bid_participant": raw["bid_part_id"],
        "ask_participant": raw["ask_part_id"],
        "seq_num": raw["seq_num"],
    }
    df = pd.DataFrame(
        {
            col: (values if col == "type" else pd.to_numeric(values, errors="coerce"))
            for col, values in source.items()
        }
    )
    df.index = index
    df.index.name = None
    # The wire interleaves QTE/TRD by arrival, leaving small local timestamp
    # inversions; a stable sort restores chronological order while keeping
    # the server's sequence within equal timestamps.
    return df.sort_index(kind="stable")
