"""Generate the sync legacy I/O layer from the async source tree.

Transforms ``src/py_bcast/_legacy/_async/`` (hand-written source) into
``src/py_bcast/_legacy/_sync/`` (generated, committed) via unasync token
rewriting, stamps a DO-NOT-EDIT header, and ruff-formats the output.

Usage:
    uv run python scripts/gen_sync.py            # regenerate in place
    uv run python scripts/gen_sync.py --check    # verify committed tree is
                                                 # up to date (exit 1 if not)
"""

from __future__ import annotations

import filecmp
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

import unasync

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src" / "py_bcast" / "_legacy" / "_async"
DST = ROOT / "src" / "py_bcast" / "_legacy" / "_sync"

# Cross-boundary swaps: names that differ between the async and sync halves
# of the shared modules (http singletons, rate limiter, vectorizer, httpx).
REPLACEMENTS = {
    "get_async_http_client": "get_http_client",
    "rate_limit_async": "rate_limit",
    "vectorize_async": "vectorize",
    "AsyncClient": "Client",
}

HEADER = (
    "# GENERATED by scripts/gen_sync.py from _legacy/_async/{name} — DO NOT EDIT.\n"
)


def generate(dst: Path) -> None:
    """Generate the sync tree from SRC into ``dst``."""
    dst.mkdir(parents=True, exist_ok=True)
    files = sorted(SRC.glob("*.py"))
    rule = unasync.Rule(
        fromdir=str(SRC) + "/",
        todir=str(dst) + "/",
        additional_replacements=REPLACEMENTS,
    )
    unasync.unasync_files([str(p) for p in files], [rule])

    for src_file in files:
        out = dst / src_file.name
        # Read with universal newlines, write LF explicitly: the output must be
        # byte-identical across platforms for the --check diff to hold.
        body = out.read_text(encoding="utf-8")
        out.write_text(
            HEADER.format(name=src_file.name) + body, encoding="utf-8", newline="\n"
        )

    subprocess.run(
        [sys.executable, "-m", "ruff", "format", "--quiet", str(dst)], check=True
    )


def check() -> int:
    """Regenerate into a temp dir and diff against the committed tree."""
    with tempfile.TemporaryDirectory() as tmp:
        fresh = Path(tmp) / "_sync"
        generate(fresh)
        expected = sorted(p.name for p in fresh.glob("*.py"))
        actual = sorted(p.name for p in DST.glob("*.py")) if DST.exists() else []
        if expected != actual:
            print(f"gen_sync --check: file sets differ: {expected} vs {actual}")
            return 1
        stale = [
            name
            for name in expected
            if not filecmp.cmp(fresh / name, DST / name, shallow=False)
        ]
        if stale:
            print(f"gen_sync --check: stale generated files: {stale}")
            print("Run: uv run python scripts/gen_sync.py")
            return 1
    return 0


if __name__ == "__main__":
    if "--check" in sys.argv:
        sys.exit(check())
    if DST.exists():
        shutil.rmtree(DST)
    generate(DST)
    print(f"generated {len(list(DST.glob('*.py')))} files into {DST}")
