"""Generate the sync I/O layers from the async source trees.

Transforms each hand-written ``_async/`` source tree into its ``_sync/``
twin (generated, committed) via unasync token rewriting, stamps a
DO-NOT-EDIT header, and ruff-formats the output.

Usage:
    uv run python scripts/gen_sync.py            # regenerate in place
    uv run python scripts/gen_sync.py --check    # verify committed trees are
                                                 # up to date (exit 1 if not)
"""

from __future__ import annotations

import filecmp
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

import unasync

ROOT = Path(__file__).resolve().parent.parent
PKG = ROOT / "src" / "py_bcast"

# (source tree, generated tree) pairs. Each backend keeps its own pair so the
# legacy/plus import isolation holds inside the generated code too.
TREES: list[tuple[Path, Path]] = [
    (PKG / "_legacy" / "_async", PKG / "_legacy" / "_sync"),
    (PKG / "_plus" / "_async", PKG / "_plus" / "_sync"),
]

# Cross-boundary swaps: names that differ between the async and sync halves
# of the shared modules (http singletons, rate limiter, vectorizer, httpx).
REPLACEMENTS = {
    "get_async_http_client": "get_http_client",
    "get_plus_async_http_client": "get_plus_http_client",
    "rate_limit_async": "rate_limit",
    "vectorize_async": "vectorize",
    "AsyncClient": "Client",
}

HEADER = "# GENERATED by scripts/gen_sync.py from {src}/{name} — DO NOT EDIT.\n"


def generate(src: Path, dst: Path) -> None:
    """Generate one sync tree from its async source tree."""
    dst.mkdir(parents=True, exist_ok=True)
    files = sorted(src.glob("*.py"))
    rule = unasync.Rule(
        fromdir=str(src) + "/",
        todir=str(dst) + "/",
        additional_replacements=REPLACEMENTS,
    )
    unasync.unasync_files([str(p) for p in files], [rule])

    src_label = src.relative_to(PKG).as_posix()
    for src_file in files:
        out = dst / src_file.name
        # Read with universal newlines, write LF explicitly: the output must be
        # byte-identical across platforms for the --check diff to hold.
        body = out.read_text(encoding="utf-8")
        out.write_text(
            HEADER.format(src=src_label, name=src_file.name) + body,
            encoding="utf-8",
            newline="\n",
        )

    subprocess.run(
        [sys.executable, "-m", "ruff", "format", "--quiet", str(dst)], check=True
    )


def check() -> int:
    """Regenerate into temp dirs and diff against the committed trees."""
    failed = 0
    for src, dst in TREES:
        with tempfile.TemporaryDirectory() as tmp:
            fresh = Path(tmp) / "_sync"
            generate(src, fresh)
            expected = sorted(p.name for p in fresh.glob("*.py"))
            actual = sorted(p.name for p in dst.glob("*.py")) if dst.exists() else []
            if expected != actual:
                print(f"gen_sync --check [{dst}]: file sets differ: {actual}")
                failed = 1
                continue
            stale = [
                name
                for name in expected
                if not filecmp.cmp(fresh / name, dst / name, shallow=False)
            ]
            if stale:
                print(f"gen_sync --check [{dst}]: stale generated files: {stale}")
                failed = 1
    if failed:
        print("Run: uv run python scripts/gen_sync.py")
    return failed


if __name__ == "__main__":
    if "--check" in sys.argv:
        sys.exit(check())
    for src, dst in TREES:
        if dst.exists():
            shutil.rmtree(dst)
        generate(src, dst)
        print(f"generated {len(list(dst.glob('*.py')))} files into {dst}")
