"""Corporate-events core for the Broadcast+ REST API.

corporateevents/{symbol} returns dividends, JCP, income and splits with the
price/volume adjustment factors (addFactor, calculatedFactor) the legacy
``bdividends`` does not carry. The hand-written async source; the sync twin is
generated by ``scripts/gen_sync.py``.
"""

from __future__ import annotations

import pandas as pd

from ..._core.exceptions import NotFoundError
from ..._core.logging import get_logger
from .transport import plus_request

logger = get_logger(__name__)

# Flat schema (column order). ``ticker`` leads so several symbols stack cleanly;
# the three date fields are Sao Paulo tz-aware; the factor columns are the
# adjustment maths the legacy feed lacks.
_CORP_COLUMNS = [
    "ticker",
    "type",
    "legal_type",
    "effective_date",
    "execution_date",
    "meeting_date",
    "previous_symbol",
    "should_adjust_price",
    "should_adjust_volume",
    "add_factor",
    "calculated_factor",
    "multiplicative_factor",
]

_DATE_COLUMNS = ("effective_date", "execution_date", "meeting_date")


def _empty_corp(ticker: str) -> pd.DataFrame:
    return pd.DataFrame({col: pd.Series(dtype="object") for col in _CORP_COLUMNS})


async def corpevents_core(ticker: str) -> pd.DataFrame:
    """Fetch corporate events with adjustment factors for one symbol.

    Raises NotFoundError if the symbol does not exist (HTTP 404). Returns an
    empty frame with the full schema if the symbol exists but has no events.
    """
    logger.debug("bcorpevents: %s", ticker)
    r = await plus_request("post", f"/stock/v1/corporateevents/{ticker}", json={})

    if r.status_code == 404:
        raise NotFoundError(ticker, kind="symbol")

    data = r.json()
    rows = data.get("data") or [] if isinstance(data, dict) else []
    if not rows:
        return _empty_corp(ticker)

    records = [
        {
            "ticker": ticker,
            "type": (e.get("type") or "").strip(),
            "legal_type": e.get("legalType", ""),
            "effective_date": e.get("effectiveDate"),
            "execution_date": e.get("executionDate"),
            "meeting_date": e.get("meetingDate"),
            "previous_symbol": e.get("previousSymbol", ""),
            "should_adjust_price": e.get("shouldAdjustPrice"),
            "should_adjust_volume": e.get("shouldAdjustVolume"),
            "add_factor": e.get("addFactor"),
            "calculated_factor": e.get("calculatedFactor"),
            "multiplicative_factor": e.get("multiplicativeFactor"),
        }
        for e in rows
    ]
    df = pd.DataFrame(records, columns=_CORP_COLUMNS)
    for col in _DATE_COLUMNS:
        ms = pd.to_numeric(df[col], errors="coerce")
        df[col] = pd.to_datetime(ms.where(ms != 0), unit="ms", utc=True).dt.tz_convert(
            "America/Sao_Paulo"
        )
    for col in ("add_factor", "calculated_factor", "multiplicative_factor"):
        df[col] = pd.to_numeric(df[col], errors="coerce")

    # The server returns events in a non-deterministic order; sort to a stable,
    # reproducible layout (most recent effective date first, then the remaining
    # fields as tie-breakers).
    return df.sort_values(
        by=["effective_date", "execution_date", "type", "add_factor"],
        ascending=False,
        na_position="last",
        kind="mergesort",
    ).reset_index(drop=True)
