"""Investment-fund cores for the Broadcast+ REST API.

Fund search (funds/v1/search) and fund detail (funds/v1/{id}). A Broadcast+
capability with no legacy equivalent. The hand-written async source; the sync
twin is generated by ``scripts/gen_sync.py``.
"""

from __future__ import annotations

import pandas as pd

from ..._core.exceptions import NotFoundError
from ..._core.logging import get_logger
from .transport import plus_request

logger = get_logger(__name__)

# Flat schema (column order) for the funds frame. ``id`` leads (the lookup key
# for bfund). Epoch-ms date fields are converted to datetime; everything else
# is taken verbatim from the server.
_FUND_COLUMNS = [
    "id",
    "symbol",
    "cnpj",
    "company",
    "trading_name",
    "manager",
    "administrator",
    "status",
    "is_active",
    "is_open",
    "is_exclusive",
    "quota",
    "net_worth",
    "minimum_investment",
    "additional_investment",
    "management_fee",
    "begin",
    "end",
    "last_quote_date",
    "profit_daily",
    "profit_monthly",
    "profit_1m",
    "profit_3m",
    "profit_6m",
    "profit_18m",
    "profit_1y",
    "profit_2y",
    "profit_3y",
    "profit_5y",
    "profit_annual",
    "anbima_class",
    "anbima_category",
    "anbima_subcategory",
    "performance_indicator",
    "performance_description",
    "qualified_investor_type",
]

_DATE_COLUMNS = ("begin", "end", "last_quote_date")


def _empty_funds() -> pd.DataFrame:
    """Empty funds frame carrying the full schema."""
    return pd.DataFrame({col: pd.Series(dtype="object") for col in _FUND_COLUMNS})


def _fund_record(f: dict) -> dict:
    """Flatten one server fund object into a unified-schema record."""

    def anbima(key: str) -> str:
        node = f.get(key) or {}
        return node.get("description", "")

    return {
        "id": f.get("id"),
        "symbol": f.get("symbol", ""),
        "cnpj": f.get("cnpj", ""),
        "company": f.get("company", ""),
        "trading_name": f.get("tradingName", ""),
        "manager": f.get("manager", ""),
        "administrator": f.get("administrator", ""),
        "status": f.get("status", ""),
        "is_active": f.get("isActive"),
        "is_open": f.get("isOpen"),
        "is_exclusive": f.get("isExclusive"),
        "quota": f.get("quota"),
        "net_worth": f.get("netWorth"),
        "minimum_investment": f.get("minimumInvestment"),
        "additional_investment": f.get("additionalInvestment"),
        "management_fee": f.get("managementFee"),
        "begin": f.get("begin"),
        "end": f.get("end"),
        "last_quote_date": f.get("lastQuoteDate"),
        "profit_daily": f.get("dailyPercentageProfitability"),
        "profit_monthly": f.get("monthlyPercentageProfitability"),
        "profit_1m": f.get("oneMonthPercentageProfitability"),
        "profit_3m": f.get("threeMonthsPercentageProfitability"),
        "profit_6m": f.get("sixMonthsPercentageProfitability"),
        "profit_18m": f.get("eighteenMonthsPercentageProfitability"),
        "profit_1y": f.get("oneYearPercentageProfitability"),
        "profit_2y": f.get("twoYearsPercentageProfitability"),
        "profit_3y": f.get("threeYearsPercentageProfitability"),
        "profit_5y": f.get("fiveYearsPercentageProfitability"),
        "profit_annual": f.get("annualPercentageProfitability"),
        "anbima_class": anbima("anbimaClass"),
        "anbima_category": anbima("anbimaCategory"),
        "anbima_subcategory": anbima("anbimaSubcategory"),
        "performance_indicator": f.get("performanceIndicator", ""),
        "performance_description": f.get("performanceDescription", ""),
        "qualified_investor_type": f.get("qualifiedInvestorType", ""),
    }


def _build_funds_frame(records: list[dict]) -> pd.DataFrame:
    """Materialize fund records into the typed frame, converting epoch-ms dates.

    Date fields are epoch-ms at Sao Paulo midnight, so they are localized to
    America/Sao_Paulo (matching the times-and-trades convention) — leaving them
    UTC would render a calendar date as the prior day's 21:00 / next 03:00. A
    zero epoch (``begin``/``end`` for open-ended funds, or a fund with no quote
    yet) becomes NaT rather than the 1970 epoch.
    """
    df = pd.DataFrame(records, columns=_FUND_COLUMNS)
    for col in _DATE_COLUMNS:
        ms = pd.to_numeric(df[col], errors="coerce")
        df[col] = pd.to_datetime(ms.where(ms != 0), unit="ms", utc=True).dt.tz_convert(
            "America/Sao_Paulo"
        )
    return df


async def funds_core(query: str) -> pd.DataFrame:
    """Search investment funds by name (minimum 3 characters).

    Returns an empty frame (full schema) if nothing matches.
    """
    logger.debug("bfunds: %s", query)
    r = await plus_request("post", "/funds/v1/search", json={"Query": query})

    data = r.json()
    funds = (data.get("funds") or []) if isinstance(data, dict) else []
    if not funds:
        return _empty_funds()

    return _build_funds_frame([_fund_record(f) for f in funds])


async def fund_core(fund_id: int) -> pd.DataFrame:
    """Fetch one fund's detail by numeric id.

    Raises NotFoundError if the id does not exist (the server answers 400 with
    "Nao foram encontrados registros" for an unknown id).
    """
    logger.debug("bfund: %s", fund_id)
    r = await plus_request("get", f"/funds/v1/{fund_id}")

    if r.status_code in (400, 404):
        raise NotFoundError(fund_id, kind="fund")

    fund = r.json()
    if not isinstance(fund, dict) or not fund.get("id"):
        raise NotFoundError(fund_id, kind="fund")

    return _build_funds_frame([_fund_record(fund)])
