"""News cores for the Broadcast+ REST API.

Section catalog (news/v1/sections), paginated headlines (news/v1/headlines),
and article content with rich tagging (news/v1/content/{id}). Distinct from the
legacy CentralMultimidia ``bnews`` (which fetches one article by a 56M-range
id) — the Plus feed is section-based and carries structured tagging. The
hand-written async source; the sync twin is generated by ``scripts/gen_sync.py``.
"""

from __future__ import annotations

import pandas as pd

from ..._core.exceptions import NotFoundError
from ..._core.logging import get_logger
from .transport import plus_request

logger = get_logger(__name__)

# ── bsections — section catalog ──────────────────────────────────────────────

_SECTION_COLUMNS = [
    "id",
    "name",
    "service",
    "minutes",
    "is_top_news",
    "is_most_read",
    "is_consolidated",
]


async def sections_core() -> pd.DataFrame:
    """Fetch the catalog of available news sections."""
    logger.debug("bsections")
    r = await plus_request("get", "/news/v1/sections")

    rows = r.json()
    if not isinstance(rows, list) or not rows:
        return pd.DataFrame(
            {col: pd.Series(dtype="object") for col in _SECTION_COLUMNS}
        )

    records = [
        {
            "id": s.get("id"),
            "name": s.get("name", ""),
            "service": s.get("service", ""),
            "minutes": s.get("minutes"),
            "is_top_news": s.get("isTopNews"),
            "is_most_read": s.get("isMostRead"),
            "is_consolidated": s.get("isConsolidated"),
        }
        for s in rows
    ]
    return pd.DataFrame(records, columns=_SECTION_COLUMNS)


# ── bheadlines — paginated headlines ─────────────────────────────────────────

_HEADLINE_COLUMNS = [
    "id",
    "time",
    "title",
    "sentiment",
    "section_id",
    "section_name",
    "service",
    "is_fast",
    "is_highlight",
]

# Server caps a page at 100 headlines (Count is ignored; PageSize sets the page
# size, CurrentPage walks pages). Bound the walk so a huge count cannot spin.
_PAGE_SIZE = 100
_MAX_PAGES = 50


def _empty_headlines() -> pd.DataFrame:
    return pd.DataFrame({col: pd.Series(dtype="object") for col in _HEADLINE_COLUMNS})


def _headline_record(h: dict) -> dict:
    section = h.get("section") or {}
    return {
        "id": h.get("id", ""),
        "time": h.get("time"),
        "title": h.get("title", ""),
        "sentiment": h.get("sentiment"),
        "section_id": section.get("id"),
        "section_name": section.get("name", ""),
        "service": section.get("service", ""),
        "is_fast": h.get("isFast"),
        "is_highlight": h.get("isHighlight"),
    }


async def headlines_core(sections: list[int], count: int) -> pd.DataFrame:
    """Fetch up to ``count`` headlines for the given section ids, newest first.

    Walks pages of 100 (the server's fixed page size) until ``count`` rows are
    collected or the feed is exhausted. ``time`` is a Sao Paulo tz-aware
    publication timestamp.
    """
    logger.debug("bheadlines: sections=%s count=%s", sections, count)

    collected: list[dict] = []
    page = 1
    while len(collected) < count and page <= _MAX_PAGES:
        r = await plus_request(
            "post",
            "/news/v1/headlines",
            json={"Sections": sections, "PageSize": _PAGE_SIZE, "CurrentPage": page},
        )
        data = r.json()
        batch = data.get("headlines") or [] if isinstance(data, dict) else []
        if not batch:
            break
        collected.extend(batch)
        if not data.get("remaining"):
            break
        page += 1

    if not collected:
        return _empty_headlines()

    df = pd.DataFrame(
        [_headline_record(h) for h in collected[:count]], columns=_HEADLINE_COLUMNS
    )
    df["time"] = pd.to_datetime(
        pd.to_numeric(df["time"], errors="coerce"), unit="ms", utc=True
    ).dt.tz_convert("America/Sao_Paulo")
    return df


# ── bnews_content — article body + tagging ───────────────────────────────────


async def content_core(content_id: int | str) -> dict:
    """Fetch one article's body and structured tagging by id.

    Returns a dict with the headline metadata, HTML ``body``, media flags, and a
    ``tagging`` sub-dict (authors, entities, locations, topics, subjects).
    Raises NotFoundError if the id does not exist or is not accessible (the
    server answers 403/404).
    """
    logger.debug("bnews_content: %s", content_id)
    r = await plus_request("get", f"/news/v1/content/{content_id}")

    if r.status_code in (403, 404):
        raise NotFoundError(content_id, kind="news content")

    data = r.json()
    headline = data.get("headline") or {}
    section = headline.get("section") or {}
    tagging = data.get("tagging") or {}

    return {
        "id": headline.get("id", str(content_id)),
        "title": headline.get("title", ""),
        "time": headline.get("time"),
        "sentiment": headline.get("sentiment"),
        "section_id": section.get("id"),
        "section_name": section.get("name", ""),
        "body": data.get("body", ""),
        "has_audio": data.get("hasAudio", False),
        "has_pdf": data.get("hasPdf", False),
        "has_video": data.get("hasVideo", False),
        "tagging": {
            "authors": tagging.get("authors") or [],
            "entities": tagging.get("entities") or [],
            "locations": tagging.get("locations") or [],
            "topics": tagging.get("mainTopics") or [],
            "subjects": tagging.get("subjects") or [],
        },
    }
