"""Reference-data cores for the Broadcast+ REST API.

Instrument metadata (quote/symbol), index composition (indexes/{index}),
and instrument logos (logo/{symbol}). Each core is the hand-written async
source; the sync twin is generated by ``scripts/gen_sync.py``.
"""

from __future__ import annotations

import pandas as pd

from ..._core.constants import normalize_exchange
from ..._core.exceptions import NotFoundError
from ..._core.logging import get_logger
from .transport import plus_request

logger = get_logger(__name__)

# ── binfo — instrument metadata ──────────────────────────────────────────────

# Flat schema (column order) for the instrument-metadata frame. ``ticker``
# leads so several symbols stack cleanly. Booleans and ids stay object-typed
# to survive an empty frame without dtype drift.
_INFO_COLUMNS = [
    "ticker",
    "name",
    "type",
    "market",
    "exchange",
    "exchange_id",
    "cvm_code",
    "currency",
    "decimal_places",
    "flag",
    "graphic_type",
    "has_book",
    "has_daily",
    "has_intraday",
    "is_realtime",
    "is_delay",
    "timezone",
]


def _empty_info() -> pd.DataFrame:
    """Empty metadata frame carrying the full schema."""
    return pd.DataFrame({col: pd.Series(dtype="object") for col in _INFO_COLUMNS})


async def info_core(symbols: list[str]) -> pd.DataFrame:
    """Fetch instrument metadata for one or more symbols.

    Unknown symbols come back in the response ``notFound`` list and are simply
    omitted from the frame; an all-unknown request yields an empty frame with
    the full schema. The endpoint returns metadata only — never price.
    """
    logger.debug("binfo: %s", symbols)
    r = await plus_request("post", "/stock/v1/quote/symbol", json={"Symbols": symbols})

    data = r.json()
    rows = data.get("data") or [] if isinstance(data, dict) else []
    if not rows:
        return _empty_info()

    records = []
    for s in rows:
        exch = s.get("exchange") or {}
        currency = s.get("currency") or {}
        tz = s.get("timeZone") or {}
        records.append(
            {
                "ticker": s.get("code", ""),
                "name": s.get("description", ""),
                "type": s.get("typeDescription", ""),
                "market": s.get("marketDescription", ""),
                "exchange": normalize_exchange(exch.get("name", "")),
                "exchange_id": exch.get("id"),
                "cvm_code": s.get("cvmCode"),
                "currency": currency.get("shortName", ""),
                "decimal_places": s.get("decimalPlaces"),
                "flag": s.get("flag", ""),
                "graphic_type": s.get("graphicType", ""),
                "has_book": s.get("hasBook"),
                "has_daily": s.get("hasDaily"),
                "has_intraday": s.get("hasIntraday"),
                "is_realtime": s.get("isRealTime"),
                "is_delay": s.get("isDelay"),
                "timezone": tz.get("name", ""),
            }
        )

    return pd.DataFrame(records, columns=_INFO_COLUMNS)


# ── bindex_members — index composition ───────────────────────────────────────

_INDEX_COLUMNS = ["index", "symbol", "relevance"]


async def index_members_core(index: str) -> pd.DataFrame:
    """Fetch the member composition of a market index with relevance weights.

    Raises NotFoundError if the index code does not exist (HTTP 404). The
    ``relevance`` weights are the index's published participation percentages.
    """
    logger.debug("bindex_members: %s", index)
    r = await plus_request("get", f"/stock/v1/indexes/{index}")

    if r.status_code == 404:
        raise NotFoundError(index, kind="index")

    members = r.json()
    if not isinstance(members, list) or not members:
        return pd.DataFrame({col: pd.Series(dtype="object") for col in _INDEX_COLUMNS})

    records = [
        {"index": index, "symbol": m.get("symbol", ""), "relevance": m.get("relevance")}
        for m in members
    ]
    df = pd.DataFrame(records, columns=_INDEX_COLUMNS)
    df["relevance"] = pd.to_numeric(df["relevance"], errors="coerce")
    return df


# ── bindexes — available index codes ─────────────────────────────────────────


async def index_list_core() -> pd.DataFrame:
    """Fetch the list of available index codes (feeds ``bindex_members``)."""
    logger.debug("bindexes")
    r = await plus_request("get", "/stock/v1/indexes")
    codes = r.json()
    codes = [c for c in codes if isinstance(c, str)] if isinstance(codes, list) else []
    return pd.DataFrame({"index": pd.Series(codes, dtype="object")})


# ── bholidays — holiday-table catalog ────────────────────────────────────────

# NOTE: only the holiday-table CATALOG (country tables) is reachable. The
# per-table holiday dates endpoint (POST /stock/v1/calendar/holidays) accepts a
# non-empty body but ignores every filter shape probed (27 variants), always
# answering "Nenhum filtro de tabela de feriados aplicado" — the filter key is
# undiscovered, so the dates themselves stay out of reach for now.
_HOLIDAY_TABLE_COLUMNS = ["id", "name"]


async def holiday_tables_core() -> pd.DataFrame:
    """Fetch the catalog of holiday tables (country/exchange calendars)."""
    logger.debug("bholidays")
    r = await plus_request("get", "/stock/v1/calendar/tables")

    data = r.json()
    tables = data.get("holidaysTables") or [] if isinstance(data, dict) else []
    if not tables:
        return pd.DataFrame(
            {col: pd.Series(dtype="object") for col in _HOLIDAY_TABLE_COLUMNS}
        )

    records = [{"id": t.get("id"), "name": t.get("name", "")} for t in tables]
    return pd.DataFrame(records, columns=_HOLIDAY_TABLE_COLUMNS)


# ── blogo — instrument logo ──────────────────────────────────────────────────


async def logo_core(symbol: str) -> bytes:
    """Fetch the PNG logo bytes for an instrument.

    Raises NotFoundError if the symbol has no logo (HTTP 404).
    """
    logger.debug("blogo: %s", symbol)
    r = await plus_request("get", f"/stock/v1/logo/{symbol}")

    if r.status_code == 404:
        raise NotFoundError(symbol, kind="logo")

    return r.content
